@echo off
setlocal enabledelayedexpansion

set "ROOT=AutoGenerated"

REM 1) 출력 루트 폴더 준비
if not exist "%ROOT%" mkdir "%ROOT%"

REM 2) 현재 존재하는 IDL 이름 목록(세미콜론으로 감싼 토큰)을 만든다: ;Foo;Bar;
set "VALID=;"
for %%F in (*.idl) do (
    set "VALID=!VALID!%%~nF;"
)

REM 3) (선택) Generated 루트에 섞여있는 .cs가 있으면 정리
REM     - 예전에 단일 출력 폴더 방식으로 생성해둔 파일들이 남아있을 때만 유용
del /q "%ROOT%\*.cs" 2>nul

REM 4) IDL별로 하위 폴더에 생성
for %%F in (*.idl) do (
    set "NAME=%%~nF"
    set "OUTDIR=%ROOT%\!NAME!"

    if not exist "!OUTDIR!" mkdir "!OUTDIR!"

    echo Processing %%F -> !OUTDIR!
    call rtiddsgen -language c# -d "!OUTDIR!" -update typefiles -ppDisable "%%F"
    call rtiddsgen -language c# -d "!OUTDIR!" -update typefiles -ppDisable "%%F" -convertToXML

    if errorlevel 1 (
        echo ERROR: Failed to process %%F
        exit /b 1
    )
)

echo VALID=!VALID!

REM 5) 현재 IDL에 없는 출력 폴더는 삭제
for /d %%D in ("%ROOT%\*") do (
  set "DNAME=%%~nxD"
  echo Checking !DNAME!

  echo !VALID! | findstr /c:";!DNAME!;" >nul

  if errorlevel 1 (
    echo DELETE %%D
    rmdir /s /q "%%D"
  ) else (
    echo KEEP %%D
  )
)

echo.
echo Done. Output is under "%ROOT%".
exit /b 0
