<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RunPostBuildEvent>Always</RunPostBuildEvent>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Rti.ConnextDds" Version="7.3.0" />
    <PackageReference Include="Rti.ConnextDds.RequestReply" Version="7.3.0" />
    <PackageReference Include="System.CommandLine" Version="2.0.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\DdsRuntimeService\DdsRuntimeService.csproj" />
    <ProjectReference Include="..\DdsTypeSupport\DdsTypeSupport.csproj" />
  </ItemGroup>

  <Target Name="PostBuild" AfterTargets="PostBuildEvent">
    <Exec Command="mkdir &quot;$(TargetDir)svc&quot;&#xD;&#xA;copy &quot;$(ProjectDir)svc\&quot; &quot;$(TargetDir)svc\&quot;&#xD;&#xA;" />
  </Target>

</Project>
